### Добавление Марселя

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "sidikov.marsel@gmail.com",
  "password": "qwerty007"
}

### Добавление Алишера

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "alisher@gmail.com",
  "password": "qwerty008"
}


### Получение всех пользователей

GET localhost:8080/api/users

### Добавление события
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "fest",
  "address": "Berlin",
  "description": "Beer party"
}

### Добавление еще одного события
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Opera",
  "address": "Leipzig",
  "description": "balet"
}

### Получение всех событий
GET localhost:8080/api/events

